name: Nucleus
description: Sets up SimCube Nucleus.

inputs:
  setupDotNet:
    description: Boolean flag which declares if dotnet should be setup.
    required: false
    default: 'true'
  dotnetVersion:
    description: Boolean flag which declares if dotnet should be setup.
    required: false
    default: '8.0.x'
  checkout:
    description: Boolean flag which declares if git checkout should take place or not by this script.
    required: false
    default: 'true'
  installNucleus:
    description: Boolean flag which declares if should install Nucleus.Cli
    required: false
    default: 'true'
  installSonarScanner:
    description: Boolean flag which declares if should install Nucleus.Cli
    required: false
    default: 'false'
  addNugetSource:
    description: Boolean flag indicates if should add nuget source.
    required: false
    default: 'false'
  PAT:
    description: PAT for read packages to get nucleus while its private.
    required: false
    default: ''

runs:
  using: composite
  steps:
   
    - if: ${{ inputs.setupDotNet == 'true' }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnetVersion }}
        
    - if: ${{ inputs.addNugetSource == 'true' }}
      shell: bash
      run: dotnet nuget add source "https://nuget.pkg.github.com/SimCubeLtd/index.json" -n simcube-github -u prom3theu5 -p ${{ inputs.PAT }} --store-password-in-clear-text
        
    - if: ${{ inputs.installNucleus == 'true' }}
      shell: bash
      run: |
        dotnet nuget locals http-cache --clear
        dotnet tool update -g Nucleus.Cli
        
    - if: ${{ inputs.installSonarScanner == 'true' }}
      shell: bash
      run: |
        dotnet nuget locals http-cache --clear
        dotnet tool update -g dotnet-sonarscanner
                
    - if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
